// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpxx5BxFbE0VDPhUT_i9At11G4yjyYjRg',
    appId: '1:822195810915:android:465910113a9069b1f1fe56',
    messagingSenderId: '822195810915',
    projectId: 'sportappdenbosch',
    databaseURL: 'https://sportappdenbosch-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sportappdenbosch.firebasestorage.app',
  );

}