// Country dialing data (ISO, name, dial code)
class CountryData {
  static const List<Map<String, String>> list = [
    {'iso': 'NL', 'name': 'Netherlands', 'code': '+31'},
    {'iso': 'BE', 'name': 'Belgium', 'code': '+32'},
    {'iso': 'FR', 'name': 'France', 'code': '+33'},
    {'iso': 'ES', 'name': 'Spain', 'code': '+34'},
    {'iso': 'IT', 'name': 'Italy', 'code': '+39'},
    {'iso': 'CH', 'name': 'Switzerland', 'code': '+41'},
    {'iso': 'GB', 'name': 'United Kingdom', 'code': '+44'},
    {'iso': 'SE', 'name': 'Sweden', 'code': '+46'},
    {'iso': 'NO', 'name': 'Norway', 'code': '+47'},
    {'iso': 'PL', 'name': 'Poland', 'code': '+48'},
    {'iso': 'DE', 'name': 'Germany', 'code': '+49'},
    {'iso': 'PT', 'name': 'Portugal', 'code': '+351'},
    {'iso': 'IE', 'name': 'Ireland', 'code': '+353'},
    {'iso': 'IS', 'name': 'Iceland', 'code': '+354'},
    {'iso': 'RO', 'name': 'Romania', 'code': '+40'},
    {'iso': 'CZ', 'name': 'Czech Republic', 'code': '+420'},
    {'iso': 'SK', 'name': 'Slovakia', 'code': '+421'},
    {'iso': 'AT', 'name': 'Austria', 'code': '+43'},
    {'iso': 'HU', 'name': 'Hungary', 'code': '+36'},
    {'iso': 'GR', 'name': 'Greece', 'code': '+30'},
    {'iso': 'DK', 'name': 'Denmark', 'code': '+45'},
    {'iso': 'FI', 'name': 'Finland', 'code': '+358'},
    {'iso': 'EE', 'name': 'Estonia', 'code': '+372'},
    {'iso': 'LV', 'name': 'Latvia', 'code': '+371'},
    {'iso': 'LT', 'name': 'Lithuania', 'code': '+370'},
    {'iso': 'BG', 'name': 'Bulgaria', 'code': '+359'},
    {'iso': 'HR', 'name': 'Croatia', 'code': '+385'},
    {'iso': 'SI', 'name': 'Slovenia', 'code': '+386'},
    {'iso': 'BA', 'name': 'Bosnia and Herzegovina', 'code': '+387'},
    {'iso': 'RS', 'name': 'Serbia', 'code': '+381'},
    {'iso': 'ME', 'name': 'Montenegro', 'code': '+382'},
    {'iso': 'MK', 'name': 'North Macedonia', 'code': '+389'},
    {'iso': 'AL', 'name': 'Albania', 'code': '+355'},
    {'iso': 'TR', 'name': 'Türkiye', 'code': '+90'},
    {'iso': 'UA', 'name': 'Ukraine', 'code': '+380'},
    {'iso': 'BY', 'name': 'Belarus', 'code': '+375'},
    {'iso': 'RU', 'name': 'Russia', 'code': '+7'},
    {'iso': 'US', 'name': 'United States', 'code': '+1'},
    {'iso': 'CA', 'name': 'Canada', 'code': '+1'},
    {'iso': 'MX', 'name': 'Mexico', 'code': '+52'},
    {'iso': 'BR', 'name': 'Brazil', 'code': '+55'},
    {'iso': 'AR', 'name': 'Argentina', 'code': '+54'},
    {'iso': 'CL', 'name': 'Chile', 'code': '+56'},
    {'iso': 'CO', 'name': 'Colombia', 'code': '+57'},
    {'iso': 'PE', 'name': 'Peru', 'code': '+51'},
    {'iso': 'VE', 'name': 'Venezuela', 'code': '+58'},
    {'iso': 'AU', 'name': 'Australia', 'code': '+61'},
    {'iso': 'NZ', 'name': 'New Zealand', 'code': '+64'},
    {'iso': 'JP', 'name': 'Japan', 'code': '+81'},
    {'iso': 'KR', 'name': 'South Korea', 'code': '+82'},
    {'iso': 'CN', 'name': 'China', 'code': '+86'},
    {'iso': 'HK', 'name': 'Hong Kong', 'code': '+852'},
    {'iso': 'TW', 'name': 'Taiwan', 'code': '+886'},
    {'iso': 'SG', 'name': 'Singapore', 'code': '+65'},
    {'iso': 'MY', 'name': 'Malaysia', 'code': '+60'},
    {'iso': 'TH', 'name': 'Thailand', 'code': '+66'},
    {'iso': 'VN', 'name': 'Vietnam', 'code': '+84'},
    {'iso': 'PH', 'name': 'Philippines', 'code': '+63'},
    {'iso': 'IN', 'name': 'India', 'code': '+91'},
    {'iso': 'PK', 'name': 'Pakistan', 'code': '+92'},
    {'iso': 'BD', 'name': 'Bangladesh', 'code': '+880'},
    {'iso': 'AE', 'name': 'United Arab Emirates', 'code': '+971'},
    {'iso': 'SA', 'name': 'Saudi Arabia', 'code': '+966'},
    {'iso': 'IL', 'name': 'Israel', 'code': '+972'},
    {'iso': 'EG', 'name': 'Egypt', 'code': '+20'},
    {'iso': 'MA', 'name': 'Morocco', 'code': '+212'},
    {'iso': 'TN', 'name': 'Tunisia', 'code': '+216'},
    {'iso': 'ZA', 'name': 'South Africa', 'code': '+27'},
    {'iso': 'NG', 'name': 'Nigeria', 'code': '+234'},
    {'iso': 'KE', 'name': 'Kenya', 'code': '+254'},
    {'iso': 'GH', 'name': 'Ghana', 'code': '+233'},
  ];
}
